homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 369
  unit_system: imperial
  time_zone: America/Phoenix
### --- Base Modules ---
logger:
  default: info

frontend:

device_tracker:
  - platform: unifi
    host: !secret unifi_host
    port: !secret unifi_port
    verify_ssl: false
    username: !secret unifi_username
    password: !secret unifi_password
http:
  api_password: !secret http_password
  server_port: 8123
  ssl_certificate: /config/ssl/fullchain.pem
  ssl_key: /config/ssl/privkey.pem

automation: !include automations.yaml
map:
updater:
config:
discovery:
history:
logbook:
sun:
weather:
  - platform: openweathermap
    api_key: !secret weather_key
    mode: hourly

### --- My Stuff ---
camera:
  - platform: uvc
    nvr: 192.168.0.30 
    port: 7080
    key: !secret uvc_key
    password: !secret uvc_password

media_player:
  - platform: plex
  - platform: webostv
    host: 192.168.0.198
    name: Living room TV
    filename: webostv.conf
    customize:
      sources:
        - livetv
        - plex
        - netflix

hue:
  bridges:
    - host: 192.168.0.236

sabnzbd:
  api_key: !secret sab_password
  host: 192.168.0.30
  name: sabnzbd
  port: 8080
  sensors:
    - current_status
    - disk_free
    - queue_count
    - speed

cover:
  - platform: myq
    username: !secret cover_username
    password: !secret cover_password
    type: chamberlain

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

### --- Disabled stuff ---
#ecovacs:
#  username: !secret ecovacs_username
#  password: !secret ecovacs_password
#  country: us
#  continent: na
#telegram_bot: !include components/telegram_bot.yaml
#notify: !include components/notify.yaml
